
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: DBSLoginApp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.ng.bluemix.net/krish123/dbsloginapp:1
        ports:
        - containerPort: 80
